#background
rootcolor = 0x{{colors.background.default.hex_stripped}}ff

#borders
maximizescreencolor = 0x{{colors.secondary.default.hex_stripped}}ff
scratchpadcolor = 0x{{colors.tertiary.default.hex_stripped}}ff
globalcolor = 0x{{colors.secondary.default.hex_stripped}}ff
overlaycolor = 0x{{colors.tertiary_container.default.hex_stripped}}ff

#jump mode
jump_label_decorate_fg_color = 0x{{colors.primary.default.hex_stripped}}ff
jump_label_decorate_bg_color = 0x{{colors.surface.default.hex_stripped}}ff
jump_label_decorate_focus_fg_color = 0x{{colors.tertiary.default.hex_stripped}}ff
jump_label_decorate_focus_bg_color = 0x{{colors.surface_variant.default.hex_stripped}}ff
jump_label_decorate_border_color = 0x{{colors.primary.default.hex_stripped}}ff

#monocle tabs
tab_bar_decorate_fg_color = 0x{{colors.primary.default.hex_stripped}}ff
tab_bar_decorate_bg_color = 0x{{colors.surface.default.hex_stripped}}ff
tab_bar_decorate_focus_fg_color = 0x{{colors.tertiary.default.hex_stripped}}ff
tab_bar_decorate_focus_bg_color = 0x{{colors.surface_variant.default.hex_stripped}}ff
tab_bar_decorate_border_color = 0x{{colors.primary.default.hex_stripped}}ff
