# background processes

## update tealdeer/tldr
exec-once=tldr --update
## start dsearch file indexer
exec-once=dsearch serve --workers 1 --root ~ --exclude-hidden
## start a polkit agent
exec-once=systemctl --user start hyprpolkitagent
## first-run UI
exec-once=~/.config/sdgos/firstrun.sh

## start DankMaterial Shell
exec-once=dms run
# UI
exec-once=ghostty

# pre-load terminal scratchpad
exec-once=sleep 2.5 && mmsg dispatch toggle_named_scratchpad,com.mitchellh.ghostty,scratchpad-term,'ghostty +new-window --title="scratchpad-term"'
exec-once=sleep 3 && mmsg dispatch toggle_named_scratchpad,com.mitchellh.ghostty,scratchpad-term,'ghostty +new-window --title="scratchpad-term"'
exec-once=sleep 3.5 && mmsg dispatch toggle_named_scratchpad,com.mitchellh.ghostty,scratchpad-term,'ghostty +new-window --title="scratchpad-term"'




