# background processes

## update tealdeer/tldr
exec-once=tldr --update
## start dsearch file indexer
exec-once=dsearch serve --workers 1 --root ~
## start a polkit agent
exec-once=systemctl --user start hyprpolkitagent
## first-run UI
exec-once=~/.config/sdgos/firstrun.sh
## auto-updates (toggle off by either removing ~/.config/SDGupdate.state or running "echo 'off' > ~/.config/SDGupdate.state")
exec-once=~/.config/sdgos/auto-update.sh

# UI
exec-once=ghostty


## start DankMaterial Shell
exec-once=dms run

