# background processes

## update tealdeer/tldr
exec-once=tldr --update
## start dsearch file indexer
exec-once=dsearch serve --workers 1 --root ~
##start a polkit agent
exec-once=systemctl --user start hyprpolkitagent

# UI

## start DankMaterial Shell
exec-once=dms run

