# link all config files
source=~/.config/mango/autostart.conf
source=~/.config/mango/binds.conf
source=~/.config/mango/decoration.conf
source=~/.config/mango/environment.conf
source=~/.config/mango/input.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/monitors.conf
source=~/.config/mango/windowrules.conf
source=~/.config/mango/matugen.conf
source=~/.config/mango/dms/colors.conf
source=~/.config/mango/dms/layout.conf
source=~/.config/mango/dms/outputs.conf
source=~/.config/mango/dms/cursor.conf
source=~/.config/mango/dms/binds.conf
