#background
rootcolor = 0x0d141cff

#borders
maximizescreencolor = 0xb8c6eaff
scratchpadcolor = 0xbfc2faff
globalcolor = 0xb8c6eaff
overlaycolor = 0x3e4372ff

#jump mode
jump_label_decorate_fg_color = 0x9bcaffff
jump_label_decorate_bg_color = 0x0d141cff
jump_label_decorate_focus_fg_color = 0xbfc2faff
jump_label_decorate_focus_bg_color = 0x414750ff
jump_label_decorate_border_color = 0x9bcaffff

#monocle tabs
tab_bar_decorate_fg_color = 0x9bcaffff
tab_bar_decorate_bg_color = 0x0d141cff
tab_bar_decorate_focus_fg_color = 0xbfc2faff
tab_bar_decorate_focus_bg_color = 0x414750ff
tab_bar_decorate_border_color = 0x9bcaffff
