windowrule=title:Floating-Menu,isfloating:1,height:0.4,width:0.4

windowrule=appid:firefox,focused_opacity:0.95,unfocused_opacity:0.85

windowrule=appid:virt-manager,focused_opacity:1,unfocused_opacity:1

# fix some issues with warframe not capturing mouse.
windowrule=appid:broken,focused_opacity:1,unfocused_opacity:1,isfullscreen:1,monitor:HDMI-A-1

layerrule=layer_name:^dms.*,animation_type_open:fade,animation_type_close:fade
layerrule=layer_name:^waybar.*,animation_type_open:slide,animation_type_close:fade